# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_EXYNOS7885) := \
	      exynos7885.dtb 
dtbo-$(CONFIG_MACH_EXYNOS7884B-A20_CIS_SER) := \
        exynos7884B-a20_cis_ser_00.dtbo \
        exynos7884B-a20_cis_ser_01.dtbo \
        exynos7884B-a20_cis_ser_03.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
